import bcrypt from 'bcryptjs';
import { DatabaseSchema } from '../src/types.js';

export function getInitialSeedData(): DatabaseSchema {
  const adminPasswordHash = bcrypt.hashSync('simo12345*', 10);
  const userPasswordHash = bcrypt.hashSync('user123456', 10);
  const now = new Date().toISOString();

  return {
    users: [
      {
        id: 'usr_admin_simo',
        name: 'Sharwar Simon (Admin)',
        email: 'simo@boalkhali.com',
        phone: '+8801819000000',
        password_hash: adminPasswordHash,
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        role: 'admin',
        status: 'active',
        bio: 'Chief Administrator of Boalkhali.com Portal.',
        created_at: now,
      },
      {
        id: 'usr_mod_arif',
        name: 'Ariful Islam (Moderator)',
        email: 'arif@boalkhali.com',
        phone: '+8801812345678',
        password_hash: userPasswordHash,
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        role: 'moderator',
        status: 'active',
        bio: 'Community moderator and Boalkhali volunteer.',
        created_at: now,
      },
      {
        id: 'usr_tanjil',
        name: 'Tanjil Ahmed',
        email: 'tanjil@example.com',
        phone: '+8801711223344',
        password_hash: userPasswordHash,
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        role: 'user',
        status: 'active',
        bio: 'Resident of Shakpura, Boalkhali.',
        created_at: now,
      }
    ],
    categories: [
      {
        id: 'cat_emergency',
        name: 'জরুরি সেবা',
        name_en: 'Emergency Services',
        slug: 'emergency',
        icon: 'ShieldAlert',
        description: 'বোয়ালখালীর পুলিশ, ফায়ার সার্ভিস, অ্যাম্বুলেন্স ও জরুরি হেল্পলাইন সমূহ।',
        sort_order: 1,
        status: 'active',
        show_on_home: true,
        created_at: now,
      },
      {
        id: 'cat_health',
        name: 'স্বাস্থ্য সেবা',
        name_en: 'Health Services',
        slug: 'health',
        icon: 'HeartPulse',
        description: 'উপজেলা স্বাস্থ্য কমপ্লেক্স, বিশেষজ্ঞ ডাক্তার, হাসপাতাল ও ফার্মেসি সেবা।',
        sort_order: 2,
        status: 'active',
        show_on_home: true,
        created_at: now,
      },
      {
        id: 'cat_transport',
        name: 'পরিবহন সেবা',
        name_en: 'Transport Services',
        slug: 'transport',
        icon: 'Bus',
        description: 'বাস, ট্রেন, রিকশা, সিএনজি, গাড়ি ভাড়া এবং কুরিয়ার সার্ভিসের বিস্তারিত।',
        sort_order: 3,
        status: 'active',
        show_on_home: true,
        created_at: now,
      },
      {
        id: 'cat_general_info',
        name: 'সাধারণ তথ্য',
        name_en: 'General Information',
        slug: 'general-info',
        icon: 'Landmark',
        description: 'বোয়ালখালী উপজেলার ইতিহাস, ইউনিয়ন পরিষদ, শিক্ষা প্রতিষ্ঠান ও দর্শনীয় স্থান।',
        sort_order: 4,
        status: 'active',
        show_on_home: true,
        created_at: now,
      },
      {
        id: 'cat_business',
        name: 'ব্যবসা ও দোকান',
        name_en: 'Businesses & Shops',
        slug: 'business',
        icon: 'Store',
        description: 'বোয়ালখালীর স্থানীয় বাজার, শপিং, রেস্টুরেন্ট এবং ক্ষুদ্র ও মাঝারি ব্যবসা।',
        sort_order: 5,
        status: 'active',
        show_on_home: true,
        created_at: now,
      },
      {
        id: 'cat_agriculture',
        name: 'কৃষি ও খামার',
        name_en: 'Agriculture & Farming',
        slug: 'agriculture',
        icon: 'Sprout',
        description: 'কৃষি অফিস, সার ও বীজ বিক্রেতা, নার্সারি এবং পোল্ট্রি-ডেইরি খামার।',
        sort_order: 6,
        status: 'active',
        show_on_home: true,
        created_at: now,
      }
    ],
    subcategories: [
      // Emergency (cat_emergency)
      {
        id: 'sub_police',
        category_id: 'cat_emergency',
        name: 'পুলিশ',
        name_en: 'Police',
        slug: 'police',
        icon: 'Shield',
        description: 'বোয়ালখালী থানা, ওসি ও ডিউটি অফিসার যোগাযোগ।',
        sort_order: 1,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_fire_service',
        category_id: 'cat_emergency',
        name: 'ফায়ার সার্ভিস',
        name_en: 'Fire Service',
        slug: 'fire-service',
        icon: 'Flame',
        description: 'বোয়ালখালী ফায়ার সার্ভিস ও সিভিল ডিফেন্স স্টেশন।',
        sort_order: 2,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_electricity',
        category_id: 'cat_emergency',
        name: 'বিদ্যুৎ অফিস',
        name_en: 'Electricity (PDB / REB)',
        slug: 'electricity',
        icon: 'Zap',
        description: 'পল্লী বিদ্যুৎ ও পিডিবি অভিযোগ কেন্দ্র এবং জরুরি নম্বর।',
        sort_order: 3,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_lawyer',
        category_id: 'cat_emergency',
        name: 'আইনজীবী',
        name_en: 'Lawyers',
        slug: 'lawyer',
        icon: 'Scale',
        description: 'বোয়ালখালীর বিজ্ঞ আইনজীবী ও আইন সহায়তাকারীগণ।',
        sort_order: 4,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_journalist',
        category_id: 'cat_emergency',
        name: 'সাংবাদিক',
        name_en: 'Journalists',
        slug: 'journalist',
        icon: 'Newspaper',
        description: 'বোয়ালখালী প্রেস ক্লাব ও স্থানীয় গণমাধ্যম প্রতিনিধি।',
        sort_order: 5,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_famous_people',
        category_id: 'cat_emergency',
        name: 'বিখ্যাত ব্যক্তিরা',
        name_en: 'Notable Figures',
        slug: 'famous-people',
        icon: 'Award',
        description: 'বোয়ালখালীর কৃতি সন্তান ও সমাজসেবকগণ।',
        sort_order: 6,
        status: 'active',
        created_at: now,
      },

      // Health (cat_health)
      {
        id: 'sub_hospital',
        category_id: 'cat_health',
        name: 'হাসপাতাল',
        name_en: 'Hospitals',
        slug: 'hospital',
        icon: 'Building2',
        description: 'উপজেলা স্বাস্থ্য কমপ্লেক্স ও বেসরকারি ক্লিনিক।',
        sort_order: 1,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_doctor',
        category_id: 'cat_health',
        name: 'ডাক্তার',
        name_en: 'Doctors',
        slug: 'doctor',
        icon: 'Stethoscope',
        description: 'মেডিসিন, শিশু ও গাইনী বিশেষজ্ঞ ডাক্তারদের চেম্বার।',
        sort_order: 2,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_ambulance',
        category_id: 'cat_health',
        name: 'অ্যাম্বুলেন্স',
        name_en: 'Ambulance',
        slug: 'ambulance',
        icon: 'Ambulance',
        description: '২৪ ঘণ্টা জরুরি অ্যাম্বুলেন্স সার্ভিস নম্বর।',
        sort_order: 3,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_pharmacy',
        category_id: 'cat_health',
        name: 'ফার্মেসি',
        name_en: 'Pharmacies',
        slug: 'pharmacy',
        icon: 'Pill',
        description: '২৪ ঘণ্টা ও স্থানীয় নির্ভরযোগ্য ওষুধের দোকান।',
        sort_order: 4,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_blood_donor',
        category_id: 'cat_health',
        name: 'রক্তদাতা',
        name_en: 'Blood Donors',
        slug: 'blood-donor',
        icon: 'Droplet',
        description: 'বোয়ালখালী ব্লাড ডোনার্স ক্লাব ও স্বেচ্ছাসেবী রক্তদাতাগণ।',
        sort_order: 5,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_pathology',
        category_id: 'cat_health',
        name: 'প্যাথলজি',
        name_en: 'Pathology & Diagnostic',
        slug: 'pathology',
        icon: 'Activity',
        description: 'ডায়াগনস্টিক ল্যাব ও টেস্ট সুবিধা।',
        sort_order: 6,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_veterinary',
        category_id: 'cat_health',
        name: 'ভেটেরিনারি',
        name_en: 'Veterinary',
        slug: 'veterinary',
        icon: 'Syringe',
        description: 'উপজেলা প্রাণিসম্পদ হাসপাতাল ও পশু চিকিৎসা কেন্দ্র।',
        sort_order: 7,
        status: 'active',
        created_at: now,
      },

      // Transport (cat_transport)
      {
        id: 'sub_bus',
        category_id: 'cat_transport',
        name: 'বাস',
        name_en: 'Bus Services',
        slug: 'bus',
        icon: 'Bus',
        description: 'বোয়ালখালী-চট্টগ্রাম শহর ও অভ্যন্তরীণ বাস রুট।',
        sort_order: 1,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_train',
        category_id: 'cat_transport',
        name: 'ট্রেন',
        name_en: 'Train Services',
        slug: 'train',
        icon: 'Train',
        description: 'গোমদণ্ডী রেলওয়ে স্টেশন ও ট্রেনের সময়সূচী।',
        sort_order: 2,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_boats',
        category_id: 'cat_transport',
        name: 'নৌযান',
        name_en: 'Boats & Ferry',
        slug: 'boats',
        icon: 'Ship',
        description: 'কালুরঘাট ফেরি ঘাট ও কর্ণফুলী নদী পারাপার।',
        sort_order: 3,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_auto_rickshaw',
        category_id: 'cat_transport',
        name: 'অটো / রিকশা',
        name_en: 'Auto & Rickshaw',
        slug: 'auto-rickshaw',
        icon: 'Car',
        description: 'সিএনজি ও অটোরিকশা স্ট্যান্ড এবং চালক তালিকা।',
        sort_order: 4,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_car_rental',
        category_id: 'cat_transport',
        name: 'গাড়ি ভাড়া',
        name_en: 'Car Rental',
        slug: 'car-rental',
        icon: 'CarTaxiFront',
        description: 'মাইক্রোবাস, প্রাইভেট কার ও হাইয়েস ভাড়া সেবা।',
        sort_order: 5,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_bike_rental',
        category_id: 'cat_transport',
        name: 'মোটরসাইকেল ভাড়া',
        name_en: 'Motorcycle & Rider',
        slug: 'bike-rental',
        icon: 'Bike',
        description: 'রাইড শেয়ারিং ও বাইক রেন্টাল সাপোর্ট।',
        sort_order: 6,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_courier',
        category_id: 'cat_transport',
        name: 'কুরিয়ার সার্ভিস',
        name_en: 'Courier Services',
        slug: 'courier',
        icon: 'Package',
        description: 'সুন্দরবন, এসএ পরিবহন ও পার্সেল পয়েন্ট।',
        sort_order: 7,
        status: 'active',
        created_at: now,
      },

      // General Info (cat_general_info)
      {
        id: 'sub_location',
        category_id: 'cat_general_info',
        name: 'অবস্থান',
        name_en: 'Location & Geography',
        slug: 'location',
        icon: 'MapPin',
        description: 'বোয়ালখালী উপজেলার ভৌগোলিক অবস্থান ও সীমানা।',
        sort_order: 1,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_info',
        category_id: 'cat_general_info',
        name: 'তথ্য',
        name_en: 'Upazila Information',
        slug: 'info',
        icon: 'Info',
        description: 'উপজেলার পরিচিতি, জনসংখ্যা ও ইতিহাস।',
        sort_order: 2,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_unions',
        category_id: 'cat_general_info',
        name: 'ইউনিয়ন',
        name_en: 'Unions',
        slug: 'unions',
        icon: 'Layers',
        description: 'বোয়ালখালীর পৌরসভা ও ৯টি ইউনিয়ন পরিষদের তথ্য।',
        sort_order: 3,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_education',
        category_id: 'cat_general_info',
        name: 'শিক্ষা',
        name_en: 'Education',
        slug: 'education',
        icon: 'GraduationCap',
        description: 'কলেজ, উচ্চ বিদ্যালয়, মাদ্রাসা ও প্রাথমিক বিদ্যালয়।',
        sort_order: 4,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_economy',
        category_id: 'cat_general_info',
        name: 'অর্থনীতি',
        name_en: 'Economy & Trade',
        slug: 'economy',
        icon: 'TrendingUp',
        description: 'অর্থনৈতিক কার্যক্রম, শিল্প কলকারখানা ও বাণিজ্য।',
        sort_order: 5,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_notable_figures',
        category_id: 'cat_general_info',
        name: 'বিখ্যাত ব্যক্তিরা',
        name_en: 'Famous Personalities',
        slug: 'notable-figures',
        icon: 'UserCheck',
        description: 'ঐতিহাসিক ব্যক্তিত্ব, কবিয়াল রমেশ শীল, বিপ্লবী বিনোদ বিহারী চৌধুরী।',
        sort_order: 6,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_visiting_spots',
        category_id: 'cat_general_info',
        name: 'ভিজিটিং স্পট',
        name_en: 'Visiting Spots',
        slug: 'visiting-spots',
        icon: 'Camera',
        description: 'বোয়ালখালীর দর্শনীয় স্থান, কালুরঘাট সেতু ও প্রাচীন মন্দির।',
        sort_order: 7,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_govt_offices',
        category_id: 'cat_general_info',
        name: 'সরকারি অফিস',
        name_en: 'Government Offices',
        slug: 'govt-offices',
        icon: 'Building',
        description: 'ইউএনও অফিস, ভূমি অফিস, শিক্ষা ও নির্বাচন অফিস।',
        sort_order: 8,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_markets',
        category_id: 'cat_general_info',
        name: 'বাজার',
        name_en: 'Markets & Bazars',
        slug: 'markets',
        icon: 'ShoppingBag',
        description: 'গোমদণ্ডী বাজার, শাকপুরা বাজার, কানুনগোপাড়া বাজার।',
        sort_order: 9,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_post_offices',
        category_id: 'cat_general_info',
        name: 'পোস্ট অফিস',
        name_en: 'Post Offices',
        slug: 'post-offices',
        icon: 'Mail',
        description: 'বোয়ালখালী প্রধান ডাকঘর (পোস্ট কোড: ৪৩৬০) ও শাখা ডাকঘর।',
        sort_order: 10,
        status: 'active',
        created_at: now,
      },

      // Business
      {
        id: 'sub_restaurants',
        category_id: 'cat_business',
        name: 'রেস্টুরেন্ট ও ক্যাফে',
        name_en: 'Restaurants & Cafes',
        slug: 'restaurants',
        icon: 'Utensils',
        description: 'বোয়ালখালীর সেরা খাবারের দোকান ও ফ্যামিলি রেস্টুরেন্ট।',
        sort_order: 1,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_electronics',
        category_id: 'cat_business',
        name: 'ইলেকট্রনিক্স ও মোবাইল',
        name_en: 'Electronics & Mobile',
        slug: 'electronics',
        icon: 'Smartphone',
        description: 'মোবাইল শপ, সার্ভিসিং ও ইলেকট্রনিক্স সামগ্রী।',
        sort_order: 2,
        status: 'active',
        created_at: now,
      },

      // Agriculture
      {
        id: 'sub_farmers',
        category_id: 'cat_agriculture',
        name: 'কৃষি পরামর্শ ও অফিস',
        name_en: 'Agri Advisory & Office',
        slug: 'agri-advisory',
        icon: 'Sprout',
        description: 'উপজেলা কৃষি সম্প্রসারণ অধিদপ্তর ও সেবা।',
        sort_order: 1,
        status: 'active',
        created_at: now,
      },
      {
        id: 'sub_seeds_fertilizer',
        category_id: 'cat_agriculture',
        name: 'সার ও বীজ বিক্রেতা',
        name_en: 'Seeds & Fertilizer',
        slug: 'seeds-fertilizer',
        icon: 'Leaf',
        description: 'উন্নত মানের বীজ, সার ও কীটনাশক বিক্রেতা।',
        sort_order: 2,
        status: 'active',
        created_at: now,
      }
    ],
    listings: [
      // 1. Police Station
      {
        id: 'lst_police_thana',
        category_id: 'cat_emergency',
        subcategory_id: 'sub_police',
        display_type: 'organization',
        title: 'বোয়ালখালী থানা (পুলিশ)',
        title_en: 'Boalkhali Police Station',
        slug: 'boalkhali-police-station',
        short_description: 'বোয়ালখালী উপজেলার প্রধান থানা ও সার্বক্ষণিক নিরাপত্তা কন্ট্রোল রুম।',
        description: 'বোয়ালখালী থানা চট্টগ্রাম জেলা পুলিশের আওতাধীন একটি গুরুত্বপূর্ণ থানা। বোয়ালখালীর আইনশৃঙ্খলা রক্ষা, যে কোনো জরুরি প্রয়োজনে দ্রুত সহায়তা প্রদান ও সাধারণ ডায়েরি (জিডি) গ্রহণে পুলিশ টিম সর্বদা নিয়োজিত।',
        image: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&auto=format&fit=crop&q=80',
        gallery: [
          'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80'
        ],
        phone: '+8801713373656',
        alt_phone: '+88031-638022',
        email: 'ocboalkhali@police.gov.bd',
        website: 'https://chittagong.police.gov.bd',
        address: 'বোয়ালখালী থানা কমপ্লেক্স, বোয়ালখালী পৌরসভা, চট্টগ্রাম',
        area: 'বোয়ালখালী সদর',
        union: 'বোয়ালখালী পৌরসভা',
        latitude: 22.3789,
        longitude: 91.9168,
        opening_hours: '২৪ ঘণ্টা খোলা (সার্বক্ষণিক জরুরি সেবা)',
        verified: true,
        featured: true,
        status: 'active',
        sort_order: 1,
        views_count: 1420,
        likes_count: 89,
        created_at: now,
        updated_at: now,
      },
      // 2. Police OC
      {
        id: 'lst_police_oc',
        category_id: 'cat_emergency',
        subcategory_id: 'sub_police',
        display_type: 'person',
        title: 'অফিসার ইনচার্জ (ওসি), বোয়ালখালী থানা',
        title_en: 'Officer-in-Charge (OC), Boalkhali Police Station',
        slug: 'officer-in-charge-oc-boalkhali',
        short_description: 'বোয়ালখালী থানার ভারপ্রাপ্ত কর্মকর্তা (ওসি)।',
        description: 'যেকোনো বড় অপরাধ প্রতিরোধ, মামলা সংক্রান্ত পরামর্শ বা জরুরি আইনি সহায়তায় সরাসরি ওসির সাথে যোগাযোগ করতে পারেন।',
        image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
        gallery: [],
        phone: '+8801713373656',
        address: 'বোয়ালখালী থানা, বোয়ালখালী, চট্টগ্রাম',
        area: 'পৌরসভা',
        union: 'বোয়ালখালী পৌরসভা',
        opening_hours: 'অফিস সময়: সকাল ৯টা - বিকাল ৫টা (জরুরি ২৪ ঘণ্টা)',
        verified: true,
        featured: true,
        status: 'active',
        sort_order: 2,
        views_count: 850,
        likes_count: 45,
        created_at: now,
        updated_at: now,
      },
      // 3. Fire Station
      {
        id: 'lst_fire_station',
        category_id: 'cat_emergency',
        subcategory_id: 'sub_fire_service',
        display_type: 'organization',
        title: 'বোয়ালখালী ফায়ার সার্ভিস ও সিভিল ডিফেন্স',
        title_en: 'Boalkhali Fire Station',
        slug: 'boalkhali-fire-station',
        short_description: 'অগ্নি দুর্ঘটনা, নদী উদ্ধার ও দুর্যোগকালীন জরুরি উদ্ধারকারী দল।',
        description: 'বোয়ালখালী ফায়ার স্টেশন যেকোনো অগ্নিকাণ্ড, সড়ক দুর্ঘটনা ও দুর্যোগে তাৎক্ষণিক রেসকিউ টিম পাঠিয়ে উদ্ধারকাজ পরিচালনা করে। অগ্নিকাণ্ডের খবর পেলেই তাৎক্ষণিক কল করুন।',
        image: 'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=800&auto=format&fit=crop&q=80',
        gallery: [
          'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=800&auto=format&fit=crop&q=80'
        ],
        phone: '+8801730009999',
        alt_phone: '999',
        address: 'শাকপুরা ফায়ার সার্ভিস মোড়, শাকপুরা, বোয়ালখালী, চট্টগ্রাম',
        area: 'শাকপুরা',
        union: 'শাকপুরা',
        latitude: 22.3725,
        longitude: 91.9211,
        opening_hours: '২৪ ঘণ্টা খোলা',
        verified: true,
        featured: true,
        status: 'active',
        sort_order: 1,
        views_count: 980,
        likes_count: 67,
        created_at: now,
        updated_at: now,
      },
      // 4. Electricity Complain
      {
        id: 'lst_palli_bidyut',
        category_id: 'cat_emergency',
        subcategory_id: 'sub_electricity',
        display_type: 'service',
        title: 'চট্টগ্রাম পল্লী বিদ্যুৎ সমিতি-১ (বোয়ালখালী জোনাল অফিস)',
        title_en: 'Chittagong Palli Bidyut Samity-1 (Boalkhali)',
        slug: 'palli-bidyut-boalkhali',
        short_description: 'বিদ্যুৎ বিপর্যয়, তার ছেঁড়া, ট্রান্সফরমার ত্রুটি ও জরুরি অভিযোগ কেন্দ্র।',
        description: 'বোয়ালখালী উপজেলার পল্লী বিদ্যুতায়ন ও সার্বক্ষণিক বিদ্যুৎ সরবরাহ তদারকি অফিস। জরুরি বিদ্যুৎ সংযোগ বিচ্ছিন্ন বা ত্রুটিতে অভিযোগ নাম্বারে যোগাযোগ করুন।',
        image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&auto=format&fit=crop&q=80',
        gallery: [],
        phone: '+8801769400222',
        alt_phone: '+8801769400223',
        address: 'গোমদণ্ডী পল্লী বিদ্যুৎ মোড়, বোয়ালখালী, চট্টগ্রাম',
        area: 'গোমদণ্ডী',
        union: 'বোয়ালখালী পৌরসভা',
        opening_hours: 'অভিযোগ কেন্দ্র: ২৪ ঘণ্টা',
        verified: true,
        featured: false,
        status: 'active',
        sort_order: 1,
        views_count: 640,
        likes_count: 32,
        created_at: now,
        updated_at: now,
      },
      // 5. Lawyer
      {
        id: 'lst_advocate_sharwar',
        category_id: 'cat_emergency',
        subcategory_id: 'sub_lawyer',
        display_type: 'person',
        title: 'অ্যাডভোকেট সারওয়ার সাইমন',
        title_en: 'Advocate Sharwar Simon',
        slug: 'advocate-sharwar-simon',
        short_description: 'চট্টগ্রাম জেলা ও দায়রা জজ আদালত এবং বোয়ালখালী আইন পরামর্শক।',
        description: 'জমিজমা সংক্রান্ত দেওয়ানী, ফৌজদারি ও চুক্তিপত্রের সঠিক আইনি সহায়তা ও আইনি নোটিশ প্রদানে বিশ্বস্ত অভিজ্ঞ আইনজীবী।',
        image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=800&auto=format&fit=crop&q=80',
        gallery: [],
        phone: '+8801819000000',
        email: 'advocate.sharwar@example.com',
        address: 'আইনজীবী ভবন, কোর্ট হিল, চট্টগ্রাম ও কানুনগোপাড়া চেম্বার, বোয়ালখালী',
        area: 'কানুনগোপাড়া',
        union: 'পোপাদিয়া',
        opening_hours: 'শনিবার - বৃহস্পতিবার: বিকাল ৫টা - রাত ৯টা',
        verified: true,
        featured: true,
        status: 'active',
        sort_order: 1,
        views_count: 510,
        likes_count: 40,
        created_at: now,
        updated_at: now,
      },
      // 6. Upazila Health Complex (Hospital)
      {
        id: 'lst_health_complex',
        category_id: 'cat_health',
        subcategory_id: 'sub_hospital',
        display_type: 'organization',
        title: 'বোয়ালখালী উপজেলা স্বাস্থ্য কমপ্লেক্স',
        title_en: 'Boalkhali Upazila Health Complex (50 Bed Hospital)',
        slug: 'boalkhali-upazila-health-complex',
        short_description: '৫০ শয্যা বিশিষ্ট সরকারি সরকারি হাসপাতাল, জরুরি বিভাগ ও আউটডোর চিকিৎসা।',
        description: 'বোয়ালখালীর প্রধান সরকারি স্বাস্থ্য সেবা প্রতিষ্ঠান। ২৪ ঘণ্টা জরুরি বিভাগ, প্রসূতি ও শিশু সেবা, বিনামূল্যে ওষুধ বিতরণ, ডিজিটাল এক্স-রে ও প্যাথলজি ল্যাব সুবিধা রয়েছে।',
        image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&auto=format&fit=crop&q=80',
        gallery: [
          'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&auto=format&fit=crop&q=80'
        ],
        phone: '+8801730324789',
        alt_phone: '+88031-638050',
        email: 'uhfpo.boalkhali@gmail.com',
        address: 'শাকপুরা চৌমুহনী সংলগ্ন, বোয়ালখালী, চট্টগ্রাম',
        area: 'শাকপুরা',
        union: 'শাকপুরা',
        latitude: 22.3685,
        longitude: 91.9284,
        opening_hours: 'জরুরি বিভাগ: ২৪ ঘণ্টা, বহির্বিভাগ: সকাল ৮:৩০ - দুপুর ২:৩০',
        verified: true,
        featured: true,
        status: 'active',
        sort_order: 1,
        views_count: 2150,
        likes_count: 128,
        created_at: now,
        updated_at: now,
      },
      // 7. Specialist Doctor
      {
        id: 'lst_dr_mohammad_ali',
        category_id: 'cat_health',
        subcategory_id: 'sub_doctor',
        display_type: 'person',
        title: 'ডাঃ মোহাম্মদ আলী (মেডিসিন ও ডায়াবেটিস বিশেষজ্ঞ)',
        title_en: 'Dr. Mohammad Ali (Medicine Specialist)',
        slug: 'dr-mohammad-ali',
        short_description: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এফসিপিএস (মেডিসিন)।',
        description: 'উচ্চ রক্তচাপ, ডায়াবেটিস, অ্যাজমা, গ্যাস্ট্রিক ও দীর্ঘমেয়াদী সাধারণ রোগের অভিজ্ঞ পরামর্শক। সিরিয়ালের জন্য চেম্বার নাম্বারে কল করুন।',
        image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=800&auto=format&fit=crop&q=80',
        gallery: [],
        phone: '+8801815667788',
        address: 'শাকপুরা সেন্ট্রাল ল্যাব ও ডায়াগনস্টিক সেন্টার, বোয়ালখালী',
        area: 'শাকপুরা',
        union: 'শাকপুরা',
        opening_hours: 'প্রতিদিন বিকাল ৪:০০ - রাত ৮:০০ (শুক্রবার বন্ধ)',
        verified: true,
        featured: true,
        status: 'active',
        sort_order: 1,
        views_count: 1120,
        likes_count: 73,
        created_at: now,
        updated_at: now,
      },
      // 8. 24/7 Ambulance Service
      {
        id: 'lst_ambulance_service',
        category_id: 'cat_health',
        subcategory_id: 'sub_ambulance',
        display_type: 'service',
        title: 'বোয়ালখালী ২৪ ঘণ্টা জরুরি অ্যাম্বুলেন্স সেবা',
        title_en: 'Boalkhali 24/7 Emergency Ambulance',
        slug: 'boalkhali-emergency-ambulance',
        short_description: 'অক্সিজেন ও আইসিইউ সুবিধাসহ চট্টগ্রাম মেডিকেল ও ঢাকা স্থানান্তরে দ্রুত সেবা।',
        description: 'বোয়ালখালী উপজেলার যেকোনো স্থান থেকে মুমূর্ষু রোগী পরিবহন ও চট্টগ্রাম মেডিকেল কলেজ হাসপাতালে জরুরি স্থানান্তরের জন্য ২৪ ঘণ্টা প্রস্তুত।',
        image: 'https://images.unsplash.com/photo-1587745416684-47953f16f02f?w=800&auto=format&fit=crop&q=80',
        gallery: [],
        phone: '+8801817554433',
        alt_phone: '+8801712998877',
        address: 'উপজেলা স্বাস্থ্য কমপ্লেক্স গেট ও গোমদণ্ডী স্টেশন মোড়',
        area: 'গোমদণ্ডী',
        union: 'বোয়ালখালী পৌরসভা',
        opening_hours: '২৪ ঘণ্টা সার্বক্ষণিক প্রস্তুত',
        verified: true,
        featured: true,
        status: 'active',
        sort_order: 1,
        views_count: 1780,
        likes_count: 95,
        created_at: now,
        updated_at: now,
      },
      // 9. Blood Donor Club
      {
        id: 'lst_blood_donors',
        category_id: 'cat_health',
        subcategory_id: 'sub_blood_donor',
        display_type: 'organization',
        title: 'বোয়ালখালী রক্তদাতা ফোরাম (ব্লাড ব্যাংক)',
        title_en: 'Boalkhali Blood Donors Forum',
        slug: 'boalkhali-blood-donors-forum',
        short_description: 'বিনামূল্যে মুমূর্ষু রোগীর জন্য রক্তদাতা খুঁজে দেওয়ার স্বেচ্ছাসেবী সংগঠন।',
        description: 'বোয়ালখালী উপজেলার তরুণদের পরিচালিত অরাজনৈতিক স্বেচ্ছাসেবী সংগঠন। এ+, বি+, ও+, এবি+ সহ যে কোনো দুর্লভ গ্রুপের রক্তের প্রয়োজনে হেল্পলাইনে যোগাযোগ করুন।',
        image: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=800&auto=format&fit=crop&q=80',
        gallery: [],
        phone: '+8801823445566',
        alt_phone: '+8801912334455',
        email: 'blood.boalkhali@gmail.com',
        address: 'গোমদণ্ডী বাজার সেন্ট্রাল পয়েন্ট, বোয়ালখালী, চট্টগ্রাম',
        area: 'গোমদণ্ডী বাজার',
        union: 'বোয়ালখালী পৌরসভা',
        opening_hours: '২৪ ঘণ্টা রক্তের অনুসন্ধান সেবা',
        verified: true,
        featured: true,
        status: 'active',
        sort_order: 1,
        views_count: 1390,
        likes_count: 154,
        created_at: now,
        updated_at: now,
      },
      // 10. Gomdandi Railway Station
      {
        id: 'lst_train_gomdandi',
        category_id: 'cat_transport',
        subcategory_id: 'sub_train',
        display_type: 'place',
        title: 'গোমদণ্ডী রেলওয়ে স্টেশন',
        title_en: 'Gomdandi Railway Station',
        slug: 'gomdandi-railway-station',
        short_description: 'চট্টগ্রাম-দোহাজারী ও কক্সবাজার রেল রুটের ঐতিহাসিক স্টেশন।',
        description: 'বোয়ালখালী উপজেলার প্রধান রেলওয়ে স্টেশন। এখান থেকে চট্টগ্রাম শহরের বটতলী স্টেশন ও দক্ষিণ চট্টগ্রামের উদ্দেশ্যে নিয়মিত ট্রেন চলাচল করে। স্টেশন মাস্টার ও টিকেট কাউন্টার সুবিধা রয়েছে।',
        image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&auto=format&fit=crop&q=80',
        gallery: [
          'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&auto=format&fit=crop&q=80'
        ],
        phone: '+8801819887766',
        address: 'পূর্ব গোমদণ্ডী, বোয়ালখালী পৌরসভা, চট্টগ্রাম',
        area: 'পূর্ব গোমদণ্ডী',
        union: 'বোয়ালখালী পৌরসভা',
        latitude: 22.3795,
        longitude: 91.9054,
        opening_hours: 'সকাল ৬:০০ - রাত ৯:০০',
        verified: true,
        featured: true,
        status: 'active',
        sort_order: 1,
        views_count: 1650,
        likes_count: 110,
        created_at: now,
        updated_at: now,
      },
      // 11. Rent a Car
      {
        id: 'lst_rent_a_car',
        category_id: 'cat_transport',
        subcategory_id: 'sub_car_rental',
        display_type: 'business',
        title: 'বোয়ালখালী রেন্ট-এ-কার ও মাইক্রোবাস সার্ভিস',
        title_en: 'Boalkhali Rent-A-Car Service',
        slug: 'boalkhali-rent-a-car',
        short_description: 'নোয়া, হাইয়েস, প্রাইভেট কার ও বিয়ে বা পারিবারিক ভ্রমণের গাড়ি ভাড়া।',
        description: 'চট্টগ্রাম শহর, বিমানবন্দর, কক্সবাজার বা দেশের যেকোনো স্থানে নিরাপদে ভ্রমণের জন্য এসি ও নন-এসি আধুনিক গাড়ি ড্রাইভারসহ ভাড়া পাওয়া যায়।',
        image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&auto=format&fit=crop&q=80',
        gallery: [],
        phone: '+8801814992211',
        alt_phone: '+8801711883344',
        address: 'কালুরঘাট সংযোগ মোড়, গোমদণ্ডী, বোয়ালখালী',
        area: 'কালুরঘাট মোড়',
        union: 'বোয়ালখালী পৌরসভা',
        opening_hours: '২৪ ঘণ্টা বুকিং চালু',
        verified: true,
        featured: false,
        status: 'active',
        sort_order: 1,
        views_count: 730,
        likes_count: 42,
        created_at: now,
        updated_at: now,
      },
      // 12. UNO Office
      {
        id: 'lst_uno_office',
        category_id: 'cat_general_info',
        subcategory_id: 'sub_govt_offices',
        display_type: 'organization',
        title: 'উপজেলা নির্বাহী অফিসার (ইউএনও) কার্যালয়, বোয়ালখালী',
        title_en: 'Upazila Nirbahi Officer (UNO) Office, Boalkhali',
        slug: 'uno-office-boalkhali',
        short_description: 'বোয়ালখালী উপজেলার প্রধান প্রশাসনিক কেন্দ্র ও সেবা দপ্তর।',
        description: 'বোয়ালখালী উপজেলার সার্বিক প্রশাসনিক কার্যক্রম, উন্নয়ন প্রকল্প তদারকি, নাগরিক সেবা ও গণশুনানি পরিচালিত হয় এই কার্যালয় থেকে।',
        image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
        gallery: [],
        phone: '+8801730331046',
        email: 'unoboalkhali@mopa.gov.bd',
        website: 'https://boalkhali.chittagong.gov.bd',
        address: 'উপজেলা পরিষদ চত্বর, বোয়ালখালী, চট্টগ্রাম',
        area: 'উপজেলা সদর',
        union: 'বোয়ালখালী পৌরসভা',
        latitude: 22.3772,
        longitude: 91.9215,
        opening_hours: 'রবিবার - বৃহস্পতিবার: সকাল ৯:০০ - বিকাল ৫:০০',
        verified: true,
        featured: true,
        status: 'active',
        sort_order: 1,
        views_count: 1980,
        likes_count: 88,
        created_at: now,
        updated_at: now,
      },
      // 13. Sir Ashutosh Govt College
      {
        id: 'lst_ashutosh_college',
        category_id: 'cat_general_info',
        subcategory_id: 'sub_education',
        display_type: 'place',
        title: 'স্যার আশুতোষ সরকারি কলেজ, বোয়ালখালী',
        title_en: 'Sir Ashutosh Government College',
        slug: 'sir-ashutosh-govt-college',
        short_description: '১৯৩৯ সালে প্রতিষ্ঠিত দক্ষিণ চট্টগ্রামের ঐতিহ্যবাহী সর্বোচ্চ বিদ্যাপীঠ।',
        description: 'কানুনগোপাড়ায় অবস্থিত এই ঐতিহাসিক কলেজটি জাতীয় বিশ্ববিদ্যালয়ের অধীনে অনার্স ও মাস্টার্স কোর্স সহ উচ্চ মাধ্যমিক শিক্ষা প্রদান করে আসছে। অসংখ্য কৃতি ব্যক্তিত্বের স্মৃতিবিজড়িত এই ক্যাম্পাস।',
        image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80',
        gallery: [
          'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80'
        ],
        phone: '+88031-638012',
        email: 'ashutoshcollege@yahoo.com',
        website: 'http://sagc.gov.bd',
        address: 'কানুনগোপাড়া, পোপাদিয়া, বোয়ালখালী, চট্টগ্রাম',
        area: 'কানুনগোপাড়া',
        union: 'পোপাদিয়া',
        latitude: 22.3551,
        longitude: 91.9542,
        opening_hours: 'সকাল ৯:০০ - বিকাল ৪:৩০ (শুক্রবার ও শনিবার বন্ধ)',
        verified: true,
        featured: true,
        status: 'active',
        sort_order: 1,
        views_count: 3200,
        likes_count: 245,
        created_at: now,
        updated_at: now,
      },
      // 14. Visiting spot - Karaldenga Temple / Hill
      {
        id: 'lst_karaldenga_hill',
        category_id: 'cat_general_info',
        subcategory_id: 'sub_visiting_spots',
        display_type: 'place',
        title: 'শ্রী শ্রী মেধা মুনি আশ্রম ও করলডেঙ্গা পাহাড়',
        title_en: 'Medhas Munir Ashram & Karaldenga Hill',
        slug: 'medhas-munir-ashram-karaldenga',
        short_description: 'ঐতিহাসিক শক্তিপীঠ ও প্রাকৃতিক সৌন্দর্যমণ্ডিত পর্যটন কেন্দ্র।',
        description: 'পৌরাণিক কাহিনী মতে রাজা সুরথ ও সমাধি বৈশ্য এখানেই দেবী দুর্গার প্রথম মৃন্ময়ী মূর্তি গড়ে পূজা করেছিলেন। সবুজ পাহাড়বেষ্টিত এই স্থান বোয়ালখালীর অন্যতম প্রধান তীর্থ ও ভ্রমণ স্থান।',
        image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
        gallery: [
          'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&auto=format&fit=crop&q=80'
        ],
        phone: '+8801815112233',
        address: 'করলডেঙ্গা পাহাড় চূড়া, করলডেঙ্গা ইউনিয়ন, বোয়ালখালী, চট্টগ্রাম',
        area: 'করলডেঙ্গা',
        union: 'আহলা করলডেঙ্গা',
        latitude: 22.3320,
        longitude: 91.9750,
        opening_hours: 'প্রতিদিন সকাল ৬:০০ - সন্ধ্যা ৬:৩০',
        verified: true,
        featured: true,
        status: 'active',
        sort_order: 1,
        views_count: 2890,
        likes_count: 210,
        created_at: now,
        updated_at: now,
      },
      // 15. Gomdandi Bazar
      {
        id: 'lst_gomdandi_bazar',
        category_id: 'cat_general_info',
        subcategory_id: 'sub_markets',
        display_type: 'place',
        title: 'গোমদণ্ডী বাজার',
        title_en: 'Gomdandi Bazar',
        slug: 'gomdandi-bazar',
        short_description: 'বোয়ালখালী উপজেলার প্রধান ও বৃহত্তম বাণিজ্যিক বাজার।',
        description: 'নিত্যপ্রয়োজনীয় জিনিসপত্র, তাজা মাছ, শাকসবজি, কাপড়, স্বর্ণালঙ্কার ও পাইকারি পণ্যের সবচেয়ে বড় কেনাকাটার কেন্দ্রস্থল।',
        image: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800&auto=format&fit=crop&q=80',
        gallery: [],
        phone: '+8801819334455',
        address: 'গোমদণ্ডী বাজার মোড়, বোয়ালখালী, চট্টগ্রাম',
        area: 'গোমদণ্ডী বাজার',
        union: 'বোয়ালখালী পৌরসভা',
        opening_hours: 'সকাল ৭:০০ - রাত ১০:০০',
        verified: true,
        featured: true,
        status: 'active',
        sort_order: 1,
        views_count: 1840,
        likes_count: 92,
        created_at: now,
        updated_at: now,
      }
    ],
    posts: [
      {
        id: 'post_1',
        user_id: 'usr_admin_simo',
        user_name: 'Sharwar Simon (Admin)',
        user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        user_role: 'admin',
        title: 'স্বাগতম Boalkhali.com পোর্টালে!',
        content: 'বোয়ালখালীর সকল নাগরিক সেবা, জরুরি যোগাযোগ ও স্থানীয় ব্যবসায়ীদের সংযুক্ত করতে আমাদের এই নতুন উন্মোচন। আপনাদের মূল্যবান মতামত ও তথ্য দিয়ে পোর্টালটি সমৃদ্ধ করতে সহযোগিতা করুন।',
        image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&auto=format&fit=crop&q=80',
        category: 'ঘোষণা',
        likes: ['usr_mod_arif', 'usr_tanjil'],
        comments_count: 2,
        status: 'approved',
        featured: true,
        created_at: now,
      },
      {
        id: 'post_2',
        user_id: 'usr_mod_arif',
        user_name: 'Ariful Islam (Moderator)',
        user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        user_role: 'moderator',
        title: 'শাকপুরা এলাকায় আগামী শুক্রবার ফ্রি মেডিকেল ক্যাম্প',
        content: 'উপজেলা স্বাস্থ্য কমপ্লেক্স ও রেড ক্রিসেন্টের যৌথ উদ্যোগে আগামী শুক্রবার শাকপুরা বহুমুখী উচ্চ বিদ্যালয় প্রাঙ্গণে বিনামূল্যে ডায়াবেটিস পরীক্ষা ও সাধারণ স্বাস্থ্য পরামর্শ দেওয়া হবে।',
        category: 'স্বাস্থ্য',
        likes: ['usr_tanjil'],
        comments_count: 1,
        status: 'approved',
        featured: false,
        created_at: now,
      }
    ],
    comments: [
      {
        id: 'comm_1',
        post_id: 'post_1',
        user_id: 'usr_tanjil',
        user_name: 'Tanjil Ahmed',
        user_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        content: 'অসাধারণ উদ্যোগ! বোয়ালখালীর মানুষের জন্য এই ধরনের ডিজিটাল প্ল্যাটফর্ম খুবই দরকার ছিল।',
        created_at: now,
      },
      {
        id: 'comm_2',
        post_id: 'post_1',
        user_id: 'usr_mod_arif',
        user_name: 'Ariful Islam (Moderator)',
        user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        content: 'সবাইকে যুক্ত হয়ে এলাকার তথ্য শেয়ার করার অনুরোধ করছি।',
        created_at: now,
      }
    ],
    messages: [
      {
        id: 'msg_1',
        conversation_id: 'conv_1',
        sender_id: 'usr_tanjil',
        receiver_id: 'usr_admin_simo',
        message: 'আসসালামু আলাইকুম। বোয়ালখালী হাসপাতালে কি নতুন কোনো শিশু ডাক্তার যুক্ত হয়েছেন?',
        attachment: undefined,
        read_at: now,
        created_at: now,
      },
      {
        id: 'msg_2',
        conversation_id: 'conv_1',
        sender_id: 'usr_admin_simo',
        receiver_id: 'usr_tanjil',
        message: 'ওয়ালাইকুম আসসালাম। হ্যাঁ, উপজেলা স্বাস্থ্য কমপ্লেক্সে নিয়মিত শিশু বিশেষজ্ঞ উপস্থিত থাকেন। আপনি স্বাস্থ্য সেবা বিভাগে বিস্তারিত তালিকা দেখতে পারেন।',
        attachment: undefined,
        read_at: now,
        created_at: now,
      }
    ],
    conversations: [
      {
        id: 'conv_1',
        participants: ['usr_tanjil', 'usr_admin_simo'],
        last_message: 'ওয়ালাইকুম আসসালাম। হ্যাঁ, উপজেলা স্বাস্থ্য কমপ্লেক্সে নিয়মিত শিশু বিশেষজ্ঞ উপস্থিত থাকেন।',
        last_message_at: now,
        created_at: now,
      }
    ],
    bookmarks: [
      {
        id: 'bm_1',
        user_id: 'usr_tanjil',
        listing_id: 'lst_police_thana',
        created_at: now,
      },
      {
        id: 'bm_2',
        user_id: 'usr_tanjil',
        listing_id: 'lst_health_complex',
        created_at: now,
      }
    ],
    settings: {
      site_name: 'Boalkhali.com',
      site_title_bn: 'বোয়ালখালী.কম',
      site_subtitle_bn: 'আপনার এলাকার প্রয়োজনীয় তথ্য ও সেবা এক জায়গায়',
      contact_phone: '+8801713373656',
      contact_email: 'info@boalkhali.com',
      address: 'বোয়ালখালী, চট্টগ্রাম, বাংলাদেশ',
      about_text: 'Boalkhali.com হলো চট্টগ্রামের বোয়ালখালী উপজেলার স্থানীয় নাগরিক তথ্য, জরুরি সেবা, স্বাস্থ্য, পরিবহন, শিক্ষা, ব্যবসা ও সম্প্রদায়ের সার্বিক উন্নয়নমূলক ডিজিটাল প্ল্যাটফর্ম।',
      emergency_notice: 'জরুরি প্রয়োজনে জাতীয় জরুরি সেবা ৯৯৯ অথবা বোয়ালখালী থানা +৮৮০১৭১৩৩৭৩৬৫৬ এ যোগাযোগ করুন।'
    }
  };
}
